Repository BigBang-Foundation/BigBang, pull requests merged in 2020-11, with the labels that each got.

#20 Remove DeFi reward tx to template address
  src/bigbang/blockchain.cpp
  src/storage/blockbase.cpp
Labels: bug

#28 Remove invalid tx for Dex
  src/bigbang/base.h
  src/bigbang/blockmaker.cpp
  src/bigbang/core.cpp
  src/bigbang/service.cpp
  src/bigbang/txpool.cpp
  src/bigbang/txpool.h
Labels: bug

#32 Fix resyncwallet bug: no balance
  src/bigbang/wallet.cpp
Labels: bug

#34 Reduce secure memory in Wallet Key
  src/crypto/crypto.cpp
  src/crypto/crypto.h
  src/crypto/key.cpp
  src/crypto/key.h
Labels: Performance

#35 Change DPoS & PoW mint rate
  src/bigbang/core.cpp
Labels: enhancement

#36 Update Dockerfile and add build & run docker image bash script
  tools/docker/Dockerfile
  tools/docker/bigbang.conf
  tools/docker/build-image.sh
  tools/docker/run-image.sh
Labels: enhancement

#38 Update Version 2.2.4
  CHANGELOG.md
  src/bigbang/version.h
Labels: documentation
